FROM registry.fedoraproject.org/fedora:28
RUN dnf install -y openssh-server
RUN ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa && \
    ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa
COPY files/bashrc /root/.bashrc
COPY files/sshd_config /etc/ssh/
COPY build/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 0600 /root/.ssh/authorized_keys
CMD ["/usr/sbin/sshd", "-D"]
