version: "2"
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - ./crack_this_container/:/opt/app/:Z
    stdin_open: true
    tty: true
  migrator:
    build: .
    volumes:
     - ./crack_this_container/:/opt/app/:Z
    links:
     - web
    command: bash -c "python3 /opt/app/manage.py makemigrations && exec python3 /opt/app/manage.py migrate --no-input"
  ssh:
    build:
      context: .
      dockerfile: ./Dockerfile.sshd
    links:
     - web
