# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

RESPONSE = $(curl -XPOST -L --data="{}" http://web:8000/api/v0/solutions)

printf "${RESPONSE}"

# exit
